name: buildroot

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: downcase actor
        run: |
          echo "actor=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: vzlogger_dockerx.Dockerfile
          tags: vzlogger_dockerx
          build-args: BUILDER=ghcr.io/${{ env.actor }}/vzloggerbuildroot:latest
